//! gRPC projection of [`PaymentApi`].
//!
//! Mirrors `rest.rs` but for gRPC transport. The `#[toolkit::grpc_contract]`
//! macro generates `PaymentApiGrpcClient` (gated on `grpc-client`) that
//! implements [`PaymentApi`] over a tonic Channel.
//!
//! `From`/`Into` impls between SDK DTOs and the prost-generated stub
//! messages live in [`bridge`] (also gated on `grpc-client`).

use toolkit_canonical_errors::CanonicalError;
use toolkit_security::SecurityContext;

use crate::contract::PaymentApi;
use crate::models::{ChargeRequest, ChargeResponse, Invoice, ListPaymentsFilter, PaymentSummary};

/// Tonic-generated stubs from the committed `.proto` file. Available only
/// when the SDK is built with the `grpc-client` feature.
#[cfg(feature = "grpc-client")]
#[allow(clippy::all, clippy::pedantic, clippy::nursery, warnings)]
pub mod stubs {
    tonic::include_proto!("api_contracts.payment.v1");
}

/// gRPC projection of [`PaymentApi`].
#[toolkit::grpc_contract(
    package = "api_contracts.payment.v1",
    service = "PaymentApi",
    stubs_module = "crate::grpc::stubs"
)]
pub trait PaymentApiGrpc: PaymentApi {
    #[rpc(name = "Charge")]
    #[idempotency_level(NotIdempotent)]
    async fn charge(
        &self,
        ctx: SecurityContext,
        req: ChargeRequest,
    ) -> Result<ChargeResponse, CanonicalError>;

    #[rpc(name = "GetInvoice")]
    #[idempotency_level(NoSideEffects)]
    #[retryable]
    async fn get_invoice(
        &self,
        ctx: SecurityContext,
        invoice_id: String,
    ) -> Result<Invoice, CanonicalError>;

    #[rpc(name = "ListPayments")]
    #[idempotency_level(NoSideEffects)]
    #[streaming]
    fn list_payments(
        &self,
        ctx: SecurityContext,
        filter: ListPaymentsFilter,
    ) -> Result<PaymentSummary, CanonicalError>;

    // The fallible open (`#[streaming] async fn`) projects onto gRPC with no
    // extra ceremony — no framing selector, because gRPC's framing is fixed by
    // the transport, and no opt-out, because gRPC expresses this shape
    // natively: tonic's client call already returns
    // `Result<Response<Streaming<T>>, Status>`, and its server trait method
    // already returns `Result<Response<Self::Stream>, Status>`. The open and
    // the messages are two phases on the wire; the generated client keeps them
    // apart instead of flattening the open into the stream's first item.
    #[rpc(name = "StreamPayments")]
    #[idempotency_level(NoSideEffects)]
    #[streaming(open = fallible)]
    async fn stream_payments(
        &self,
        ctx: SecurityContext,
        filter: ListPaymentsFilter,
    ) -> Result<PaymentSummary, toolkit_canonical_errors::CanonicalError>;
}

// `From<Primitive> for stubs::*Request` impls for methods with a single
// primitive wire param (e.g. `get_invoice(invoice_id: String)`) are
// auto-generated by the `#[toolkit::grpc_contract]` macro itself — no
// hand-written bridge module is needed.
