//! Builds and renders the generated registry.
//!
//! Lives in the library rather than only in the `regen_registry` binary so the
//! freshness test can recompute the expected content in-process. Shelling out to
//! `cargo run` from inside `cargo test` would nest one cargo invocation inside
//! another and contend for the same build lock.

use crate::ReferenceOracle;
use crate::runner::run_evaluation_suite;
use bss_fixtures::{
    Corpus, IntegrityViolation, Registry, VariantStatus, check_integrity, check_kind_coverage,
};

const HEADER: &str = "\
# GENERATED by `cargo run -p bss-fixtures-conformance --bin regen_registry`.
# Do not hand-edit: CI asserts regeneration is diff-clean, and a regeneration is
# committed on its own.
#
# `oracle` and `publish` together open pricing's FixtureGate. No flag is set by
# hand - each is earned by a passing run.

";

#[derive(Debug, thiserror::Error)]
pub enum GenError {
    #[error("corpus integrity violations: {0:#?}")]
    Integrity(Vec<IntegrityViolation>),
    #[error("serialising the registry: {0}")]
    Serialise(#[from] toml::ser::Error),
}

/// Derives the registry from the corpus. Every flag is earned: `oracle` comes
/// from an actual suite run, and the other two stay false until their owners
/// exist.
///
/// # Errors
///
/// Returns [`GenError::Integrity`] if the corpus does not hold together — a
/// stale registry must never be generated over a broken corpus.
pub fn build(corpus: &Corpus) -> Result<Registry, GenError> {
    let mut violations = check_integrity(corpus);
    // Completeness too: the generator is exactly where an ungated kind must stop
    // the build, because the registry it writes is what the publish gate reads.
    violations.extend(check_kind_coverage(corpus));
    if !violations.is_empty() {
        return Err(GenError::Integrity(violations));
    }

    let report = run_evaluation_suite(&ReferenceOracle, corpus);

    let mut variants: Vec<VariantStatus> = Vec::new();
    for meta in &corpus.families {
        let green = report.is_green_for(meta.family);
        for kind in &meta.gates {
            variants.push(VariantStatus {
                kind: *kind,
                oracle: green,
                // Earned when pricing's validator runs the publish cases.
                publish: false,
                // Earned when rating's evaluator reproduces the corpus.
                rating: false,
            });
        }
    }
    variants.sort_by_key(|v| format!("{:?}", v.kind));

    Ok(Registry { variants })
}

/// Renders the registry to its committed file form.
///
/// # Errors
///
/// Returns [`GenError::Serialise`] if the registry cannot be serialised.
pub fn render(registry: &Registry) -> Result<String, GenError> {
    Ok(format!("{HEADER}{}", toml::to_string(registry)?))
}

/// The full generated file content for a corpus.
///
/// # Errors
///
/// Returns [`GenError`] if the corpus fails its integrity checks or the
/// registry cannot be serialised.
pub fn render_for(corpus: &Corpus) -> Result<String, GenError> {
    render(&build(corpus)?)
}

#[cfg(test)]
#[path = "registry_gen_tests.rs"]
mod registry_gen_tests;
