//! Builds and renders the generated registry.
//!
//! A **pure function of (corpus, earned publish set)**. It runs the oracle
//! itself, because the oracle lives in this crate; it cannot run pricing's
//! validator, because an evaluator must not reach a gear even transitively and
//! this crate is therefore a dev-dependency of the gear rather than the other
//! way round. So the second half arrives as an argument and the generator never
//! learns who ran what.
//!
//! The consequence is that the **gear owns the generated file**: the only build
//! in which both halves are visible is pricing's `regen_registry` example, which
//! compiles with dev-dependencies and can therefore see this crate without it
//! entering the production graph. The freshness assertion lives beside it, in
//! the gear's `tests/corpus_publish.rs`. There is exactly one authority on the
//! file's content — two crates each asserting a different expectation is how a
//! generated file starts flapping.
//!
//! Build and render stay in the library rather than only in that example so the
//! freshness test can recompute the expected content in-process. Shelling out to
//! `cargo run` from inside `cargo test` would nest one cargo invocation inside
//! another and contend for the same build lock.

use crate::ReferenceOracle;
use crate::runner::run_evaluation_suite;
use bss_fixtures::{
    Corpus, IntegrityViolation, ModelKind, Registry, VariantStatus, check_integrity,
    check_kind_coverage, check_publish_case_coverage,
};

const HEADER: &str = "\
# GENERATED by `cargo run -p bss-pricing --example regen_registry`.
# Do not hand-edit: CI asserts regeneration is diff-clean, and a regeneration is
# committed on its own.
#
# `oracle` and `publish` together open pricing's FixtureGate. No flag is set by
# hand - each is earned by a passing run, and the two runs have different owners:
# the reference oracle earns `oracle`, pricing's PublishValidator earns `publish`.

";

#[derive(Debug, thiserror::Error)]
pub enum GenError {
    #[error("corpus integrity violations: {0:#?}")]
    Integrity(Vec<IntegrityViolation>),
    #[error("serialising the registry: {0}")]
    Serialise(#[from] toml::ser::Error),
}

/// Derives the registry from the corpus and an already-earned publish set.
///
/// Every flag is earned by a run. `oracle` comes from a suite run this function
/// performs; `publish` comes from `earned_publish`, which the caller obtained
/// from [`crate::run_publish_suite`] — the caller being the only build that can
/// see both a validator and this crate. `rating` stays false until rating's
/// evaluator exists.
///
/// Deliberately **not** a runner of both halves: this function must stay pure in
/// its two inputs so the freshness test and the regeneration example compute the
/// same bytes from the same arguments.
///
/// # Errors
///
/// Returns [`GenError::Integrity`] if the corpus does not hold together — a
/// stale registry must never be generated over a broken corpus.
pub fn build(corpus: &Corpus, earned_publish: &[ModelKind]) -> Result<Registry, GenError> {
    let mut violations = check_integrity(corpus);
    // Completeness too: the generator is exactly where an ungated kind must stop
    // the build, because the registry it writes is what the publish gate reads.
    violations.extend(check_kind_coverage(corpus));
    // And the other half of the same gate. A kind with no publish case can never
    // earn `publish`, so its gate is shut permanently -- which in the generated
    // file is indistinguishable from a kind that ran and failed. Absent coverage
    // must be a named build failure here, for the same reason and in the same
    // place as an ungated kind.
    violations.extend(check_publish_case_coverage(corpus));
    if !violations.is_empty() {
        return Err(GenError::Integrity(violations));
    }

    let report = run_evaluation_suite(&ReferenceOracle, corpus);

    let mut variants: Vec<VariantStatus> = Vec::new();
    for meta in &corpus.families {
        let green = report.is_green_for(meta.family);
        for kind in &meta.gates {
            variants.push(VariantStatus {
                kind: *kind,
                oracle: green,
                // Earned by pricing's validator reproducing the publish cases;
                // handed in, because this crate cannot reach the gear.
                publish: earned_publish.contains(kind),
                // Earned when rating's evaluator reproduces the corpus.
                rating: false,
            });
        }
    }
    variants.sort_by_key(|v| format!("{:?}", v.kind));

    Ok(Registry { variants })
}

/// Renders the registry to its committed file form.
///
/// # Errors
///
/// Returns [`GenError::Serialise`] if the registry cannot be serialised.
pub fn render(registry: &Registry) -> Result<String, GenError> {
    Ok(format!("{HEADER}{}", toml::to_string(registry)?))
}

/// The full generated file content for a corpus and an earned publish set.
///
/// # Errors
///
/// Returns [`GenError`] if the corpus fails its integrity checks or the
/// registry cannot be serialised.
pub fn render_for(corpus: &Corpus, earned_publish: &[ModelKind]) -> Result<String, GenError> {
    render(&build(corpus, earned_publish)?)
}

#[cfg(test)]
#[path = "registry_gen_tests.rs"]
mod registry_gen_tests;
