//! Create the `role_assignments` table — runs after `m20260521_000001`
//! because the `role_definition_id` FK references `role_definitions(id)`.
//! The DDL branches on `sea_orm::DatabaseBackend` so the same migration
//! runs against `Postgres` (production) and `SQLite` (smoke tests / demos).

use sea_orm::{ConnectionTrait, Statement};
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

// ---------------------------------------------------------------------------
// Postgres variant.
// ---------------------------------------------------------------------------

// The FK is named explicitly so the SQLSTATE-23503 classifier in
// `role_assignment_repo` / `role_definition_repo` keeps refining typed
// variants (`RoleDefinitionMissing`, `RoleDefinitionAssignmentsExist`)
// instead of falling back to `Conflict` if Postgres ever changes its
// autogenerated `<table>_<column>_fkey` scheme or a DBA recreates the
// table with a different default.
const PG_CREATE_ROLE_ASSIGNMENTS: &str = "
CREATE TABLE role_assignments (
    id                  uuid         PRIMARY KEY,
    role_definition_id  uuid         NOT NULL
        CONSTRAINT role_assignments_role_definition_id_fkey
        REFERENCES role_definitions (id) ON DELETE RESTRICT,
    principal_id        text         NOT NULL,
    principal_type      text         NOT NULL,
    scope               text         NOT NULL,
    scope_depth         integer      NOT NULL,
    tenant_id           uuid,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now(),
    created_by          text         NOT NULL
)";

const PG_UP_STATEMENTS: &[&str] = &[
    PG_CREATE_ROLE_ASSIGNMENTS,
    "CREATE UNIQUE INDEX uq_assignment
        ON role_assignments (role_definition_id, principal_type, principal_id, scope)",
    "CREATE INDEX idx_role_assignments_principal
        ON role_assignments (principal_type, principal_id)",
    "CREATE INDEX idx_role_assignments_role
        ON role_assignments (role_definition_id)",
    "CREATE INDEX idx_role_assignments_scope_prefix
        ON role_assignments (scope text_pattern_ops)",
    "CREATE INDEX idx_role_assignments_scope_depth
        ON role_assignments (scope_depth DESC, id DESC)",
    // Composite covering index for the `get_subject_assignments` hot
    // path: filter by `(principal_type, principal_id)` then return rows
    // already ordered by `(scope_depth DESC, id DESC)` so the planner
    // can skip the explicit Sort step.
    "CREATE INDEX idx_role_assignments_principal_scope_depth
        ON role_assignments (principal_type, principal_id, scope_depth DESC, id DESC)",
    "CREATE INDEX idx_role_assignments_tenant_id
        ON role_assignments (tenant_id)
        WHERE tenant_id IS NOT NULL",
    // Keyset index for `GET /rbac/v1/role-assignments`, which paginates by
    // `(created_at DESC, id DESC)` (see
    // `role_assignment_repo::list`). Without this, broad or
    // unrestricted list requests fall back to a sequential scan + sort
    // instead of an index-backed keyset query.
    "CREATE INDEX idx_role_assignments_created_at_id
        ON role_assignments (created_at DESC, id DESC)",
];

// `DROP TABLE` cascades to every index, CHECK constraint, and FK
// defined on the table, so explicit `DROP INDEX` calls are unnecessary.
const PG_DOWN_STATEMENTS: &[&str] = &["DROP TABLE IF EXISTS role_assignments"];

// ---------------------------------------------------------------------------
// SQLite variant.
// ---------------------------------------------------------------------------
//
// Differences from the Postgres variant:
//
// * `uuid` columns become `text` (SeaORM serialises `Uuid` to text on
//   SQLite already).
// * `timestamptz NOT NULL DEFAULT now()` → `text NOT NULL DEFAULT (CURRENT_TIMESTAMP)`.
// * The `idx_role_assignments_scope_prefix` index drops the
//   `text_pattern_ops` operator class — SQLite has no operator class
//   hints; the plain B-tree index still satisfies `LIKE 'prefix%'`
//   prefix queries with the default `BINARY` collation.

// FK constraint name mirrors the Postgres variant. SQLite reports
// anonymous FK violations as `FOREIGN KEY constraint failed` without
// surfacing the constraint name, so the classifier matches on the
// referencing column set (`role_definition_id`) rather than this name
// on SQLite; the name is kept symmetric for parity and so any future
// SQLite version that *does* surface the name works without code
// changes.
const SQLITE_CREATE_ROLE_ASSIGNMENTS: &str = "
CREATE TABLE role_assignments (
    id                  text         PRIMARY KEY,
    role_definition_id  text         NOT NULL
        CONSTRAINT role_assignments_role_definition_id_fkey
        REFERENCES role_definitions (id) ON DELETE RESTRICT,
    principal_id        text         NOT NULL,
    principal_type      text         NOT NULL,
    scope               text         NOT NULL,
    scope_depth         integer      NOT NULL,
    tenant_id           text,
    created_at          text         NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at          text         NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by          text         NOT NULL
)";

const SQLITE_UP_STATEMENTS: &[&str] = &[
    SQLITE_CREATE_ROLE_ASSIGNMENTS,
    "CREATE UNIQUE INDEX uq_assignment
        ON role_assignments (role_definition_id, principal_type, principal_id, scope)",
    "CREATE INDEX idx_role_assignments_principal
        ON role_assignments (principal_type, principal_id)",
    "CREATE INDEX idx_role_assignments_role
        ON role_assignments (role_definition_id)",
    "CREATE INDEX idx_role_assignments_scope_prefix
        ON role_assignments (scope)",
    "CREATE INDEX idx_role_assignments_scope_depth
        ON role_assignments (scope_depth DESC, id DESC)",
    "CREATE INDEX idx_role_assignments_principal_scope_depth
        ON role_assignments (principal_type, principal_id, scope_depth DESC, id DESC)",
    "CREATE INDEX idx_role_assignments_tenant_id
        ON role_assignments (tenant_id)
        WHERE tenant_id IS NOT NULL",
    "CREATE INDEX idx_role_assignments_created_at_id
        ON role_assignments (created_at DESC, id DESC)",
];

const SQLITE_DOWN_STATEMENTS: &[&str] = &["DROP TABLE IF EXISTS role_assignments"];

// ---------------------------------------------------------------------------
// Migration dispatch.
// ---------------------------------------------------------------------------

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let backend = manager.get_database_backend();
        let conn = manager.get_connection();
        let statements: &[&str] = match backend {
            sea_orm::DatabaseBackend::Postgres => PG_UP_STATEMENTS,
            sea_orm::DatabaseBackend::Sqlite => SQLITE_UP_STATEMENTS,
            // `DatabaseBackend` is `#[non_exhaustive]` as of SeaORM 2.0, so the
            // unsupported case is a wildcard rather than a `MySql` arm: any backend
            // outside the PostgreSQL/SQLite pair this module targets must fail fast
            // instead of falling through to SQL written for a different dialect.
            other => {
                return Err(DbErr::Migration(format!(
                    "rbac migrations: unsupported database backend {other:?}"
                )));
            }
        };
        for sql in statements {
            conn.execute_raw(Statement::from_string(backend, (*sql).to_owned()))
                .await?;
        }
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let backend = manager.get_database_backend();
        let conn = manager.get_connection();
        let statements: &[&str] = match backend {
            sea_orm::DatabaseBackend::Postgres => PG_DOWN_STATEMENTS,
            sea_orm::DatabaseBackend::Sqlite => SQLITE_DOWN_STATEMENTS,
            // `DatabaseBackend` is `#[non_exhaustive]` as of SeaORM 2.0, so the
            // unsupported case is a wildcard rather than a `MySql` arm: any backend
            // outside the PostgreSQL/SQLite pair this module targets must fail fast
            // instead of falling through to SQL written for a different dialect.
            other => {
                return Err(DbErr::Migration(format!(
                    "rbac migrations: unsupported database backend {other:?}"
                )));
            }
        };
        for sql in statements {
            conn.execute_raw(Statement::from_string(backend, (*sql).to_owned()))
                .await?;
        }
        Ok(())
    }
}
