//! `FxRepo` — the DB plumbing for FX & multi-currency (Slice 5): the mutable
//! `ledger_fx_rate` "latest known" store (upserted by the `RateSyncJob` / ingest
//! endpoint, read by [`RateSource`](crate::infra::fx::rate_source::RateSource) at
//! lock time) and the immutable per-lock `ledger_fx_rate_snapshot` (frozen on a
//! journal line via `journal_line.rate_snapshot_ref`).
//!
//! **Scoping.** `ledger_fx_rate` is reference data — exchange rates are not
//! BOLA-sensitive object data, so it carries no resource axis. It is, however,
//! still read/written through the `SecureORM` runner with a tenant-only
//! `Scopable` (`no_resource`/`no_owner`/`no_type`, like `chain_state`): the
//! toolkit's `DBRunner`/`DBRunnerInternal` executor is sealed, so a gear cannot
//! get a raw `&DatabaseConnection` to run an un-secured query — the only
//! mechanically available path for the `tenant_id` predicate is
//! `.secure().scope_with(&AccessScope::for_tenant(tenant))`. The snapshot table
//! IS object-scoped (`rate_id` resource axis) and so takes the caller's compiled
//! [`AccessScope`] for SQL-level BOLA, exactly like the other secured reads/writes
//! in this gear.
//!
//! `ledger_fx_rate` is upserted out-of-txn (reference-data sync, no posting
//! transaction); the snapshot insert is likewise a single scoped insert. NEITHER
//! is wired into the live posting paths in this slice — see
//! [`RateLocker`](crate::infra::fx::rate_locker::RateLocker).

use chrono::{DateTime, Utc};
use sea_orm::{ActiveValue::Set, ColumnTrait, Condition, EntityTrait};
use toolkit_db::secure::{AccessScope, SecureEntityExt, SecureInsertExt, SecureOnConflict};
use toolkit_db::{DBProvider, DbError};
use uuid::Uuid;

use crate::domain::model::RepoError;
use crate::infra::storage::entity::{fx_rate, fx_rate_snapshot};

/// One immutable `ledger_fx_rate_snapshot` row to freeze for a single lock — the
/// rate [`RateSource`](crate::infra::fx::rate_source::RateSource) resolved,
/// captured verbatim so a re-read reproduces the exact translation regardless of
/// later provider revisions. `rate_id` is generated by the repo
/// ([`Uuid::now_v7`]) and returned to the caller, who stamps it onto each
/// translated line's `rate_snapshot_ref`. The snapshot is append-only (a
/// `BEFORE UPDATE OR DELETE` trigger rejects mutation), so a provider revision
/// only ever INSERTs a new row.
pub struct NewRateSnapshot {
    pub tenant_id: Uuid,
    pub base_currency: String,
    pub quote_currency: String,
    pub rate_micro: i64,
    pub as_of: DateTime<Utc>,
    pub provider: String,
    pub stale: bool,
    pub fallback_order: i32,
    pub triangulated_via: Option<String>,
}

/// One `ledger_fx_rate` row to upsert — the mutable "latest known" rate the
/// [`RateSyncJob`](crate::infra::jobs::rate_sync::RateSyncJob) and the
/// `POST /fx/rates` ingest endpoint refresh. Upsert-keyed on `(tenant_id,
/// base_currency, quote_currency, provider)`; on a PK conflict only the quote
/// moves (`rate_micro` / `as_of` / `fallback_order` / `updated_at`). A parameter
/// object (not a long arg list) — the fields are exactly the row's columns.
pub struct NewFxRate {
    pub tenant_id: Uuid,
    pub base_currency: String,
    pub quote_currency: String,
    pub provider: String,
    pub rate_micro: i64,
    pub as_of: DateTime<Utc>,
    pub fallback_order: i32,
}

/// SeaORM-backed FX rate-store + per-lock snapshot repository.
#[derive(Clone)]
pub struct FxRepo {
    db: DBProvider<DbError>,
}

impl FxRepo {
    #[must_use]
    pub fn new(db: DBProvider<DbError>) -> Self {
        Self { db }
    }

    /// UPSERT one `ledger_fx_rate` row for `(tenant, base, quote, provider)` — the
    /// "latest known" rate the `RateSyncJob` / ingest endpoint refreshes. On a PK
    /// conflict the row's `rate_micro`, `as_of`, `fallback_order` and `updated_at`
    /// are overwritten (the tuple identity — tenant/pair/provider — is immutable;
    /// only the quote moves). `updated_at` is stamped from `Utc::now()` (passed in
    /// the active model and mirrored in the conflict update) rather than a SQL
    /// `now()`, so the stored ingest-time matches the value `SeaORM` round-trips on
    /// both backends.
    ///
    /// Reference data, not BOLA-object data: scoped by the tenant axis only via
    /// `AccessScope::for_tenant(tenant)` (the entity is `no_resource`). The
    /// `SecureOnConflict` builder additionally refuses to put `tenant_id` in the
    /// update set, so an upsert can never re-tenant a rate row.
    ///
    /// # Errors
    /// [`RepoError::Db`] on a scope or storage failure.
    pub async fn upsert_rate(&self, rate: &NewFxRate) -> Result<(), RepoError> {
        let conn = self
            .db
            .conn()
            .map_err(|e| RepoError::Db(format!("conn: {e}")))?;
        let scope = AccessScope::for_tenant(rate.tenant_id);
        let now = Utc::now();
        let am = fx_rate::ActiveModel {
            tenant_id: Set(rate.tenant_id),
            base_currency: Set(rate.base_currency.clone()),
            quote_currency: Set(rate.quote_currency.clone()),
            provider: Set(rate.provider.clone()),
            rate_micro: Set(rate.rate_micro),
            as_of: Set(rate.as_of),
            fallback_order: Set(rate.fallback_order),
            updated_at: Set(now),
        };
        let on_conflict = SecureOnConflict::<fx_rate::Entity>::columns([
            fx_rate::Column::TenantId,
            fx_rate::Column::BaseCurrency,
            fx_rate::Column::QuoteCurrency,
            fx_rate::Column::Provider,
        ])
        .update_columns([
            fx_rate::Column::RateMicro,
            fx_rate::Column::AsOf,
            fx_rate::Column::FallbackOrder,
            fx_rate::Column::UpdatedAt,
        ])
        .map_err(|e| RepoError::Db(format!("ledger_fx_rate on_conflict: {e}")))?;
        fx_rate::Entity::insert(am.clone())
            .secure()
            .scope_with_model(&scope, &am)
            .map_err(|e| RepoError::Db(format!("ledger_fx_rate scope: {e}")))?
            .on_conflict(on_conflict)
            .exec(&conn)
            .await
            .map_err(|e| RepoError::Db(format!("upsert ledger_fx_rate: {e}")))?;
        Ok(())
    }

    /// All provider rows in the `ledger_fx_rate` store for one `(tenant, base,
    /// quote)` pair — the candidate set
    /// [`RateSource`](crate::infra::fx::rate_source::RateSource) orders by the
    /// configured provider precedence and screens for staleness. Returns the raw
    /// rows (one per provider); ordering/selection is the resolver's job. Reference
    /// data, tenant-axis scope only (`AccessScope::for_tenant`).
    ///
    /// # Errors
    /// [`RepoError::Db`] on a scope or storage failure.
    pub async fn latest_rates(
        &self,
        tenant: Uuid,
        base: &str,
        quote: &str,
    ) -> Result<Vec<fx_rate::Model>, RepoError> {
        let conn = self
            .db
            .conn()
            .map_err(|e| RepoError::Db(format!("conn: {e}")))?;
        let scope = AccessScope::for_tenant(tenant);
        let rows = fx_rate::Entity::find()
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(fx_rate::Column::TenantId.eq(tenant))
                    .add(fx_rate::Column::BaseCurrency.eq(base))
                    .add(fx_rate::Column::QuoteCurrency.eq(quote)),
            )
            .all(&conn)
            .await
            .map_err(|e| RepoError::Db(format!("list ledger_fx_rate: {e}")))?;
        Ok(rows)
    }

    /// Insert ONE immutable `ledger_fx_rate_snapshot` row from a resolved rate,
    /// generating `rate_id = Uuid::now_v7()` and returning it (the value the
    /// caller stamps onto each line's `rate_snapshot_ref`). The snapshot IS
    /// object-scoped (`rate_id` resource axis), so it takes the caller's compiled
    /// [`AccessScope`] and inserts via `.secure().scope_with_model` — SQL-level
    /// BOLA, exactly like the other secured writes. Append-only: the table's
    /// `BEFORE UPDATE OR DELETE` trigger rejects any later mutation.
    ///
    /// # Errors
    /// [`RepoError::Db`] on a scope or storage failure.
    pub async fn insert_snapshot(
        &self,
        scope: &AccessScope,
        snap: &NewRateSnapshot,
    ) -> Result<Uuid, RepoError> {
        let conn = self
            .db
            .conn()
            .map_err(|e| RepoError::Db(format!("conn: {e}")))?;
        // Idempotent freeze (spec §2): a snapshot is keyed by the immutable rate
        // identity `(tenant, base, quote, provider, as_of, fallback_order,
        // rate_micro)` (`uq_fx_rate_snapshot_lock`), so a re-lock of the SAME rate
        // — an idempotent post replay, or a second cross-currency entry at the same
        // published rate — REUSES the existing snapshot rather than inserting a
        // duplicate (which the constraint would reject). `rate_micro` is part of the
        // identity (codex#1 / m032): a provider/manual CORRECTION at the SAME
        // `as_of` carries a DIFFERENT rate, so it must freeze a NEW snapshot — never
        // dedupe onto the stale one (which would stamp a `rate_snapshot_ref` that no
        // longer reproduces the posted functional amount). The read-first dedups the
        // (sequential) replay; a rare concurrent first-freeze of the same rate may
        // still lose the insert race and surface as a retryable error.
        if let Some(existing) = fx_rate_snapshot::Entity::find()
            .secure()
            .scope_with(scope)
            .filter(
                Condition::all()
                    .add(fx_rate_snapshot::Column::TenantId.eq(snap.tenant_id))
                    .add(fx_rate_snapshot::Column::BaseCurrency.eq(snap.base_currency.clone()))
                    .add(fx_rate_snapshot::Column::QuoteCurrency.eq(snap.quote_currency.clone()))
                    .add(fx_rate_snapshot::Column::Provider.eq(snap.provider.clone()))
                    .add(fx_rate_snapshot::Column::AsOf.eq(snap.as_of))
                    .add(fx_rate_snapshot::Column::FallbackOrder.eq(snap.fallback_order))
                    .add(fx_rate_snapshot::Column::RateMicro.eq(snap.rate_micro)),
            )
            .one(&conn)
            .await
            .map_err(|e| RepoError::Db(format!("find ledger_fx_rate_snapshot: {e}")))?
        {
            return Ok(existing.rate_id);
        }
        let rate_id = Uuid::now_v7();
        let am = fx_rate_snapshot::ActiveModel {
            tenant_id: Set(snap.tenant_id),
            rate_id: Set(rate_id),
            base_currency: Set(snap.base_currency.clone()),
            quote_currency: Set(snap.quote_currency.clone()),
            rate_micro: Set(snap.rate_micro),
            as_of: Set(snap.as_of),
            provider: Set(snap.provider.clone()),
            stale: Set(snap.stale),
            fallback_order: Set(snap.fallback_order),
            triangulated_via: Set(snap.triangulated_via.clone()),
        };
        fx_rate_snapshot::Entity::insert(am.clone())
            .secure()
            .scope_with_model(scope, &am)
            .map_err(|e| RepoError::Db(format!("ledger_fx_rate_snapshot scope: {e}")))?
            .exec(&conn)
            .await
            .map_err(|e| RepoError::Db(format!("insert ledger_fx_rate_snapshot: {e}")))?;
        Ok(rate_id)
    }

    /// Scoped read-back of the frozen `ledger_fx_rate_snapshot` for `(tenant,
    /// rate_id)`, or `None` when absent — the audit surface that reproduces a
    /// line's exact lock. SQL-level BOLA: a foreign tenant yields no row.
    ///
    /// # Errors
    /// [`RepoError::Db`] on a scope or storage failure.
    pub async fn read_snapshot(
        &self,
        scope: &AccessScope,
        tenant: Uuid,
        rate_id: Uuid,
    ) -> Result<Option<fx_rate_snapshot::Model>, RepoError> {
        let conn = self
            .db
            .conn()
            .map_err(|e| RepoError::Db(format!("conn: {e}")))?;
        let row = fx_rate_snapshot::Entity::find()
            .secure()
            .scope_with(scope)
            .filter(
                Condition::all()
                    .add(fx_rate_snapshot::Column::TenantId.eq(tenant))
                    .add(fx_rate_snapshot::Column::RateId.eq(rate_id)),
            )
            .one(&conn)
            .await
            .map_err(|e| RepoError::Db(format!("read ledger_fx_rate_snapshot: {e}")))?;
        Ok(row)
    }
}
