//! Typed inputs for the [`GatewayProvider`](crate::GatewayProvider) abstraction.

use bytes::Bytes;
use http::uri::{Authority, Scheme, Uri};

use crate::error::GatewayError;

/// The stable name of a gear, as declared in `#[toolkit::gear(name = ...)]`.
///
/// Used as the registration key by a [`GatewayProvider`](crate::GatewayProvider).
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct GearName(String);

impl GearName {
    /// Wraps a gear name.
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self(name.into())
    }

    /// Returns the gear name as a string slice.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for GearName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl From<&str> for GearName {
    fn from(value: &str) -> Self {
        Self(value.to_owned())
    }
}

impl From<String> for GearName {
    fn from(value: String) -> Self {
        Self(value)
    }
}

/// A specific instance of a gear, identified by its stable gear name plus an
/// opaque, unique instance identifier (e.g. a UUID generated by the directory
/// service).
///
/// A [`ProxyRegistry`](crate::registry::ProxyRegistry) stores routes per
/// `GearInstance` so that multiple instances of the same gear can be registered
/// and deregistered independently.
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct GearInstance {
    gear: GearName,
    instance_id: std::sync::Arc<str>,
}

impl GearInstance {
    /// Creates an instance key from a gear name and an instance identifier.
    #[must_use]
    pub fn new(gear: GearName, instance_id: impl AsRef<str>) -> Self {
        Self {
            gear,
            instance_id: std::sync::Arc::from(instance_id.as_ref()),
        }
    }

    /// Returns the gear name.
    #[must_use]
    pub fn gear(&self) -> &GearName {
        &self.gear
    }

    /// Returns the opaque instance identifier.
    #[must_use]
    pub fn instance_id(&self) -> &str {
        &self.instance_id
    }
}

/// An `OpenAPI` document handed to a [`GatewayProvider`](crate::GatewayProvider),
/// in whichever form the caller already has — avoiding a forced clone or
/// re-serialization at the call site.
#[derive(Clone)]
pub enum OpenApiSpec<'a> {
    /// An owned document.
    Owned(Box<utoipa::openapi::OpenApi>),
    /// A borrowed document.
    Borrowed(&'a utoipa::openapi::OpenApi),
    /// A document already serialized to JSON bytes.
    SerializedJson(Bytes),
}

// `utoipa::openapi::OpenApi` does not implement `Debug`, so we cannot derive it.
// The document itself is large and not useful in logs; report only the variant
// (and byte length for the serialized form).
impl std::fmt::Debug for OpenApiSpec<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Owned(_) => f.write_str("OpenApiSpec::Owned(..)"),
            Self::Borrowed(_) => f.write_str("OpenApiSpec::Borrowed(..)"),
            Self::SerializedJson(bytes) => f
                .debug_tuple("OpenApiSpec::SerializedJson")
                .field(&bytes.len())
                .finish(),
        }
    }
}

/// The network location of a gear's HTTP server: a scheme plus an authority
/// (host and optional port).
///
/// The request path and query are taken from the inbound request at forward
/// time, so they are intentionally **not** stored here.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Endpoint {
    scheme: Scheme,
    authority: Authority,
}

impl Endpoint {
    /// Builds an endpoint from a scheme and authority.
    #[must_use]
    pub fn new(scheme: Scheme, authority: Authority) -> Self {
        Self { scheme, authority }
    }

    /// Parses an endpoint from a base URI such as `http://calculator:8080`.
    ///
    /// Any path, query, or fragment on `uri` is ignored — only the scheme and
    /// authority are retained.
    ///
    /// # Errors
    /// Returns [`GatewayError::InvalidEndpoint`] if `uri` cannot be parsed, is
    /// missing a scheme or an authority, or uses a scheme other than `http` or
    /// `https` (the only transports the proxy forwards over).
    pub fn parse(uri: &str) -> Result<Self, GatewayError> {
        let parsed: Uri =
            uri.parse()
                .map_err(|err: http::uri::InvalidUri| GatewayError::InvalidEndpoint {
                    uri: uri.to_owned(),
                    reason: err.to_string(),
                })?;
        let parts = parsed.into_parts();
        let scheme = parts.scheme.ok_or_else(|| GatewayError::InvalidEndpoint {
            uri: uri.to_owned(),
            reason: "missing scheme".to_owned(),
        })?;
        if scheme != Scheme::HTTP && scheme != Scheme::HTTPS {
            return Err(GatewayError::InvalidEndpoint {
                uri: uri.to_owned(),
                reason: format!("unsupported scheme '{scheme}' (expected http or https)"),
            });
        }
        let authority = parts
            .authority
            .ok_or_else(|| GatewayError::InvalidEndpoint {
                uri: uri.to_owned(),
                reason: "missing authority (host)".to_owned(),
            })?;
        Ok(Self { scheme, authority })
    }

    /// Returns the endpoint scheme (e.g. `http`).
    #[must_use]
    pub fn scheme(&self) -> &Scheme {
        &self.scheme
    }

    /// Returns the endpoint authority (host and optional port).
    #[must_use]
    pub fn authority(&self) -> &Authority {
        &self.authority
    }
}

#[cfg(test)]
mod tests {
    use super::{Endpoint, GearInstance, GearName, OpenApiSpec};
    use crate::error::GatewayError;
    use bytes::Bytes;
    use http::uri::{Authority, Scheme};

    #[test]
    fn gear_name_roundtrips() {
        let name = GearName::from("calculator");
        assert_eq!(name.as_str(), "calculator");
        assert_eq!(name.to_string(), "calculator");
        assert_eq!(GearName::new("calculator"), name);
    }

    #[test]
    fn gear_name_from_owned_string() {
        let name = GearName::from(String::from("billing"));
        assert_eq!(name.as_str(), "billing");
    }

    #[test]
    fn gear_instance_exposes_gear_and_id() {
        let instance = GearInstance::new(GearName::from("calc"), "calc-1");
        assert_eq!(instance.gear().as_str(), "calc");
        assert_eq!(instance.instance_id(), "calc-1");
        // Same gear + id compare equal (and hash-equal) so the registry can key on them.
        assert_eq!(
            instance,
            GearInstance::new(GearName::from("calc"), "calc-1")
        );
    }

    #[test]
    fn endpoint_new_from_parts() {
        let endpoint = Endpoint::new(Scheme::HTTP, Authority::from_static("gear:8080"));
        assert_eq!(endpoint.scheme().as_str(), "http");
        assert_eq!(endpoint.authority().as_str(), "gear:8080");
    }

    #[test]
    fn openapi_spec_debug_hides_body_but_names_variant() {
        // The custom Debug impl must not print the (potentially huge) document
        // body; it only needs to identify the variant. Assert the variant name
        // is present without pinning the exact format string.
        let owned = OpenApiSpec::Owned(Box::new(utoipa::openapi::OpenApiBuilder::new().build()));
        assert!(format!("{owned:?}").contains("Owned"));

        let doc = utoipa::openapi::OpenApiBuilder::new().build();
        let borrowed = OpenApiSpec::Borrowed(&doc);
        assert!(format!("{borrowed:?}").contains("Borrowed"));

        let serialized = OpenApiSpec::SerializedJson(Bytes::from_static(b"{}"));
        assert!(format!("{serialized:?}").contains("SerializedJson"));
    }

    #[test]
    fn endpoint_parse_extracts_scheme_and_authority() {
        let endpoint = Endpoint::parse("http://calculator:8080").expect("valid endpoint");
        assert_eq!(endpoint.scheme().as_str(), "http");
        assert_eq!(endpoint.authority().as_str(), "calculator:8080");
    }

    #[test]
    fn endpoint_parse_ignores_path_and_query() {
        let endpoint =
            Endpoint::parse("https://gear.svc/ignored?x=1").expect("valid endpoint with path");
        assert_eq!(endpoint.scheme().as_str(), "https");
        assert_eq!(endpoint.authority().as_str(), "gear.svc");
    }

    #[test]
    fn endpoint_parse_rejects_non_http_scheme() {
        // Only http/https are forwardable; anything else must be rejected so a
        // stray directory entry cannot steer the proxy at an unexpected transport.
        for uri in ["ftp://gear:21", "file:///etc/passwd", "ws://gear:8080"] {
            let err = Endpoint::parse(uri).expect_err("non-http scheme rejected");
            assert!(
                matches!(err, GatewayError::InvalidEndpoint { .. }),
                "expected InvalidEndpoint for {uri}, got {err:?}"
            );
        }
    }

    #[test]
    fn endpoint_parse_rejects_missing_scheme() {
        let err = Endpoint::parse("calculator:8080").expect_err("scheme required");
        assert!(matches!(err, GatewayError::InvalidEndpoint { .. }));
    }

    #[test]
    fn endpoint_parse_rejects_empty() {
        let err = Endpoint::parse("").expect_err("empty is invalid");
        assert!(matches!(err, GatewayError::InvalidEndpoint { .. }));
    }
}
